let alimento = {
  a_g_omega3: 0,
  a_g_omega6: 0,
  a_g_trans: 0,
  a_grasos_monosat: 0,
  a_grasos_polisat: 0,
  a_grasos_sat: 0,
  acido_folico: 0,
  acido_pantotenico: 0,
  biotina: 0,
  calcio: 0,
  carbohidratos: 0,
  cobre: 0,
  colesterol: 0,
  energia: 0,
  fibra: 0,
  fosforo: 0,
  grasas_totales: 0,
  hierro: 0,
  humedad: 0,
  magnesio: 0,
  manganeso: 0,
  potasio: 0,
  proteinas: 0,
  riboflavina: 0,
  selenio: 0,
  sodio: 0,
  tiamina: 0,
  yodo: 0,
  zinc: 0,
  vit_a: 0,
  vit_b6: 0,
  vit_b12: 0,
  vit_c: 0,
  vit_d: 0,
  vit_e: 0,
  vit_k: 0
}

export default alimento
